#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: letmein
#POSTGRESQL_HOST: 192.168.1.216
POSTGRESQL_HOST: 192.168.0.58
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: slavas21@gmail.com
EMAIL_PASSWORD: syqv tfhc wvee kfdp
VERIFY_EMAIL_HOST: http://localhost:8085